### ISSUE TITLE
OrionExplorer.com is not OrionExplorer?

### ISSUE THREAD

**Issue by LeandroGuillen** [VM9/orion-explorer-php-frame-work#7]
If I visit orionexplorer.com I am directed to a different web site that has nothing to do with this software in this repo. May be a hack?

**Comment by LeonanCarvalho** [comment]
Hi We shutdown the host because we're moving the Orion Explorer to Fiware Node in Uberlândia

We're sorry for the inconvenience, apparently someone has taken your IP. 
We will change the DNS to not cause confusion to users.

**Comment by LeandroGuillen** [comment]
Let me know when you have a new domain or the old one fixed. Thanks!

**Comment by LeonanCarvalho** [comment]
Now available again, at http://orionexplorer.com

May have some issues because we need update OrionExplorer lib to suport the latest API version
